- name: Check if sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_stat

- name: Change SSH port
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?Port "
    line: "Port 1024"
    state: present
  when: sshd_config_stat.stat.exists
  notify: Restart SSH